#!/bin/bash
# scripts/generate_report.sh
# Generates the final 14-question report from all experiment results.
#
# Usage: scripts/generate_report.sh
#        scripts/generate_report.sh --single E02

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$ROOT_DIR/reports"

mkdir -p "$REPORTS_DIR"

SINGLE=""
if [[ "$1" == "--single" ]]; then
  SINGLE="$2"
fi

if [[ -n "$SINGLE" ]]; then
  echo "[generate_report] Generating report for $SINGLE..."
  cd "$ROOT_DIR/umbrella"
  elixir -e "Lab.Runner.CLI.main([\"$SINGLE\"])" 2>/dev/null || true
  echo "  Report: experiments/${SINGLE}_*/report.md"
else
  echo "[generate_report] Generating final aggregated report..."

  # Run all experiments that have data
  DATA_DIRS=$(ls -d "$ROOT_DIR"/data/e* 2>/dev/null || true)

  if [[ -z "$DATA_DIRS" ]]; then
    echo "  No experiment data found. Run experiments first:"
    echo "    scripts/run_experiment.sh E02"
    exit 1
  fi

  # The final report will be generated by the Reporter in commit 39
  # For now, just list what's available
  echo "  Available experiment data:"
  for d in $DATA_DIRS; do
    exp_id=$(basename "$d" | tr '[:lower:]' '[:upper:]')
    echo "    $exp_id -> $d"
  done

  echo ""
  echo "  Final report generation is implemented in Phase 4 (commit 39)."
  echo "  For now, individual reports are at experiments/E##_*/report.md"
fi
